# Generated by Django 5.0.3 on 2024-04-22 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunha',
            fields=[
                ('ma_cn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_cn', models.CharField(max_length=20)),
                ('sdt_cn', models.IntegerField(max_length=10)),
                ('email_cn', models.EmailField(max_length=254)),
                ('diachi_cn', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Danhmucphong',
            fields=[
                ('madanhmuc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tendanhmuc', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('ma_kh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_kh', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('sdt_kh', models.IntegerField(max_length=10)),
                ('email_kh', models.EmailField(max_length=254)),
                ('diachi_kh', models.CharField(max_length=20)),
                ('cccd', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('maphong', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tieude', models.CharField(max_length=50)),
                ('mota', models.CharField(max_length=200)),
                ('ttnt', models.BooleanField(verbose_name='Có Nội Thất')),
                ('gia', models.IntegerField(max_length=5)),
                ('diachi', models.CharField(max_length=50)),
                ('dientich', models.IntegerField(max_length=5)),
                ('hinhanh', models.ImageField(upload_to='')),
                ('danhmuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_muc', to='app.danhmucphong')),
            ],
        ),
        migrations.CreateModel(
            name='Lichxemphong',
            fields=[
                ('malichxem', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gia', models.IntegerField()),
                ('tgxem', models.DateTimeField()),
                ('diachi_phong', models.CharField(max_length=200)),
                ('email_kh', models.EmailField(max_length=254)),
                ('sdt_kh', models.CharField(max_length=20)),
                ('ten_kh_xem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_xem_phong_ten_kh', to='app.khachhang')),
                ('ma_phong_xem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_xem_phong_ma_phong', to='app.phong')),
            ],
        ),
        migrations.CreateModel(
            name='Chitiethopdong',
            fields=[
                ('mahopdong', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tiencoc', models.IntegerField()),
                ('giaphong', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ngaykihopdong', models.DateField()),
                ('ngayketthuchopdong', models.DateField()),
                ('tenchunha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hop_dong_ten_cn', to='app.chunha')),
                ('ten_kh_thue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hop_dong_ten_kh', to='app.khachhang')),
                ('ma_phong_thue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hop_dong_ma_phong', to='app.phong')),
            ],
        ),
    ]
