# Generated by Django 5.0.3 on 2024-04-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_danhmucgia_rename_danhmucphong_danhmucquan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhmucgia',
            name='tendanhmucgia',
            field=models.CharField(max_length=20),
        ),
    ]
