# Generated by Django 5.0.3 on 2024-04-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_danhmucgia_tendanhmucgia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chitiethopdong',
        ),
        migrations.DeleteModel(
            name='Chunha',
        ),
    ]
